name: LAB 1 - Primer workflow básico

on: push

jobs:
  comandos-basicos:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir mensaje personalizado
        run: echo "Hola, este es mi primer workflow de GitHub Actions"

      - name: Listar contenido del repositorio
        run: ls -la
